version: '3.4'

services:
  api:
    image: client-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'clients'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - api-db:/var/lib/postgres

volumes:
  api-db: